apiVersion: v1
kind: Pod
metadata:
  name: mysite-pod
  labels:
    function: webserver
    class: cis-92
spec:
  containers:
  - name: httpd
    image: ghcr.io/ooperlooper/cis-92:milestone-5.0
    resources:
      limits:
        cpu: 500m 
        memory: 512Mi
        ephemeral-storage: 10M
    livenessProbe:
      httpGet:
        path: /polls/
        port: 8000
      initialDelaySeconds: 30
      periodSeconds: 30
    ports:
    - containerPort: 8000
    env:
    - name: SECRET_KEY
      value: "blahblah"
    - name: PORT
      value: "8000"
    - name: DB_NAME
      value: "mysite"     
    - name: DB_USER
      value: "postgres"   
    - name: DB_PASSWORD
      value: "django"      
    - name: DB_HOST
      value: "postgres"







